### ISSUE TITLE
Link to your Amazon AMI

### ISSUE THREAD

**Issue by ProGamerGov** [crowsonkb/deep_dream#3]
You said you had an already setup AMI here: https://www.reddit.com/r/deepdream/comments/4t2jbw/my_custom_wallpaperprintsized_image_capable/d5expuo?context=3

Could you please share it?

**Comment by crowsonkb** [comment]
https://us-west-2.console.aws.amazon.com/ec2/v2/home?region=us-west-2#LaunchInstanceWizard:ami=ami-15fc3175

You should be able to clone this repo into it and things should work. Some notes:

- Make sure deep_dream_test.py works. It runs on the CPU by default but accepts the parameter --gpus 0 (on g2.2xlarge) and --gpus 0 1 2 3 (on g2.8xlarge) to run on GPU.
- Run code in this project with python3, not python. There is no virtualenv here and 'python' will start the system python2.7. All of the pathlib errors you have had are due to pathlib not being backported to python2, for instance.

**Comment by crowsonkb** [comment]
Also, the 'scales' parameter to dream() has gone away and I haven't updated the documentation yet. Use 'min_size' instead (it has a reasonable default).

**Comment by ProGamerGov** [comment]
Thank you so much for sharing the AMI!
