### ISSUE TITLE
Using the VGG Manga model?

### ISSUE THREAD

**Issue by ProGamerGov** [crowsonkb/deep_dream#4]
A while back, a user posted Deepdreams using a model trained on Manga images. He linked to the model.

The post can be found here: 

https://www.reddit.com/r/deepdream/comments/3v9pkt/deepdream_model_trained_on_manga_comics/

Images using the model can be found here: https://imgur.com/a/8EaI8

He posted a link to the model here: https://www.reddit.com/r/deepdream/comments/3vtglt/link_to_manganet_pretrained_model/

The model can be found here:

http://illustration2vec.net/
https://github.com/rezoo/illustration2vec

You mention [here](https://www.reddit.com/r/deepdream/comments/4t2jbw/my_custom_wallpaperprintsized_image_capable/d5e5qha) that you can use other models. Can you explain how if it's different than the default models?

**Comment by crowsonkb** [comment]
OK so let's look at the unmodified model first:

```python
ILLUST2VEC = dd.CNNData('illust2vec/illust2vec_tag.prototxt', 'illust2vec/illust2vec_tag_ver200.caffemodel', (127, 127, 127))
cnn = dd.CNN(ILLUST2VEC, cpu_workers=0, gpus=[0])
for layer in cnn.layers():
    print(layer, list(cnn.net.blobs[layer].shape[1:]))
```

```
conv1_1 [64, 224, 224]
pool1 [64, 112, 112]
conv2_1 [128, 112, 112]
pool2 [128, 56, 56]
conv3_1 [256, 56, 56]
conv3_2 [256, 56, 56]
pool3 [256, 28, 28]
conv4_1 [512, 28, 28]
conv4_2 [512, 28, 28]
pool4 [512, 14, 14]
conv5_1 [512, 14, 14]
conv5_2 [512, 14, 14]
pool5 [512, 7, 7]
conv6_1 [1024, 7, 7]
conv6_2 [1024, 7, 7]
conv6_3 [1024, 7, 7]
conv6_4 [1539, 7, 7]
pool6 [1539, 1, 1]
prob [1539, 1, 1]
```

**Comment by crowsonkb** [comment]
This looks pretty standard and easy to modify. I made a new CNNData tuple containing the deploy prototxt, the model, and since I don't know the per-channel mean used for training yet I just put a reasonable default in.

Looking at the start of the deploy prototxt:

```
name: "CaffeNet"
input: "data"
input_dim: 50
input_dim: 3
input_dim: 224
input_dim: 224
```

we need to modify it to force backpropagation on and to lower the minibatch size (since we will only process one image at a time, not 50, and wish to avoid large memory allocations on model load.)

```
name: "CaffeNet"
force_backward: true
input: "data"
input_dim: 1
input_dim: 3
input_dim: 224
input_dim: 224
```

At the end of the stack of layers we find an average pooling layer right before the final sigmoid activation layer that outputs the probability of each tag. Since we'll be using different image sizes than 224x224, we won't have a 7x7 input to pool6 anymore (which expects it) and it will break. We could just *truncate* the layer stack, discarding any layers after the one that won't work, but caffe provides a better solution:

```
layer {
  name: "pool6"
  type: "Pooling"
  bottom: "conv6_4"
  top: "pool6"
  pooling_param {
    pool: AVE
    kernel_size: 7
    stride: 1
  }
}
```

to

```
layer {
  name: "pool6"
  type: "Pooling"
  bottom: "conv6_4"
  top: "pool6"
  pooling_param {
    pool: AVE
    global_pooling: true
  }
}
```

telling the pool6 layer to take *any* size feature map and average it down to a 1x1.

**Comment by crowsonkb** [comment]
Lastly, we need the per-channel mean for the training data set. They have helpfully provided an image_mean.npy file, which is the per-pixel mean for the training data set (3chx224x224). We don't use per-pixel means since we don't always use 224x224 images. So I brought up ipython / jupyter:

```python
import numpy as np
m = np.load('image_mean.npy')
m.mean(1).mean(1)
```

and got ```array([ 164.76139251,  167.47864617,  181.13838569])```.

which is pretty different from the imagenet per-channel mean. At this point we can enter the mean into the original call to the CNN constructor:

```python
ILLUST2VEC = dd.CNNData('illust2vec/illust2vec_tag.prototxt', 'illust2vec/illust2vec_tag_ver200.caffemodel', (164.76, 167.48, 181.14))
```

and now I am having weird animated heads show up in the clouds of my images when I run dream(), so it looks like it worked. :)

**Comment by ProGamerGov** [comment]
So I made the modifications to the prototext file and brought it up in ipython / jupyter. I then received the following error:

`ILLUST2VEC = dd.CNNData('illust2vec/illust2vec_tag.prototxt', 'illust2vec/illust2vec_tag_ver200.caffemodel', (164.76, 167.48, 181.14))`


```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-7-2fad972b10a6> in <module>()
----> 1 ILLUST2VEC = dd.CNNData('illust2vec/illust2vec_tag.prototxt', 'illust2vec/illust2vec_tag_ver200.caffemodel', (164.76, 167.48, 181.14))

NameError: name 'dd' is not defined
```

**Comment by crowsonkb** [comment]
```import deep_dream as dd``` is a shortcut I often use to reduce typing, sorry. :)

**Comment by ProGamerGov** [comment]
That fixed that issue! Now the only other issue seems to be with cell 4 and 5. 


Cell 4:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-35-5dbcb04f41e0> in <module>()
      1 input_img = Image.open('kodim/img0024.jpg').resize((2385, 1590), Image.LANCZOS)
----> 2 show(input_img)

<ipython-input-34-d9350abe01c7> in show(img)
      2 
      3 def show(img):
----> 4     print(cnn.classify(img, 5))
      5     if isinstance(img, np.ndarray):
      6         img = deep_dream.to_image(img)

NameError: name 'cnn' is not defined

```


Cell 5:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-36-d32837300cae> in <module>()
----> 1 output_img = cnn.dream(input_img, {'inception_4a/pool_proj': 1},
      2                        scales=7*4, n=2, per_octave=8, step_size=4)
      3 show(output_img)

NameError: name 'cnn' is not defined

```

**Comment by crowsonkb** [comment]
I actually just meant to go back and put the mean into the original constructor, resulting in the definition of ILLUST2VEC followed by the definition of cnn.

Also, you're going to have to change the layer name to one of the layers that's actually in this network and get rid of the 'scales' argument.

**Comment by ProGamerGov** [comment]
Thanks! It works now though I do still get this error in cell 4: 

```
100%|█████████████████████████████████████| 47.4M/47.4M [00:52<00:00, 961Kpix/s]
/home/ubuntu/deep_dream/deep_dream/deep_dream.py:340: VisibleDeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future
  return [(prob[i], self.categories[i]) for i in indices]
[(array([[[[ 0.]]]], dtype=float32), '0'), (array([[[[ 0.]]]], dtype=float32), '0'), (array([[[[ 0.]]]], dtype=float32), '0'), (array([[[[ 0.]]]], dtype=float32), '0'), (array([[[[ 0.]]]], dtype=float32), '0')]
```

---

I also figured I'd upload the modified prototxt for others, here: https://gist.github.com/ProGamerGov/ef5ce8f11f3a8d798a1610d3e9a8ce38

**Comment by crowsonkb** [comment]
I think it's still trying to classify the images and we haven't provided a list of categories. Just remove the line `print(cnn.classify(img, 5))` from the 'show' function.

The first one I tried, conv5_1, gave me faces.
